[package]
name = "Vulx"
version = "0.1.0"
edition = "2021"

[features]
default = []
util = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = { version = "0.36", features = ["linked"] }
png = "0.17.11"